apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: nginx:latest
              imagePullPolicy: IfNotPresent
              command:
                - ls
          restartPolicy: OnFailure
