apiVersion: v1 # K8S API Version
kind: Pod # Object Type
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.7.9
      ports:
        - containerPort: 80
    - name: springapp
      image: yanivomc/spring-music:latest
      ports:
        - containerPort: 8080
      volumeMounts:
       - name: redis-persistent-storage  # name must match the volume name defined in volumes
         mountPath: /data/redis # mount path within the container
  volumes:
    - name: redis-persistent-storage # Volume name
      emptyDir: {} # Volume type